---
name: Linting

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.12"

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v7.0.1
      - name: 🏗 Set up uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          enable-cache: true
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: 🐍 Install Python
        run: uv python install
      - name: 🏗 Install dependencies
        run: uv sync --locked
      - name: 🚀 Run ruff linter
        run: uv run ruff check --output-format=github .
      - name: 🚀 Run ruff formatter
        run: uv run ruff format --check .

  prek-hooks:
    name: prek-hooks
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v7.0.1
      - name: 🏗 Set up uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          enable-cache: true
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: 🐍 Install Python
        run: uv python install
      - name: 🏗 Install dependencies
        run: uv sync --locked
      - name: 🚀 Check Python AST
        run: uv run prek run check-ast --all-files
      - name: 🚀 Check for case conflicts
        run: uv run prek run check-case-conflict --all-files
      - name: 🚀 Check docstring is first
        run: uv run prek run check-docstring-first --all-files
      - name: 🚀 Check that executables have shebangs
        run: uv run prek run check-executables-have-shebangs --all-files
      - name: 🚀 Check JSON files
        run: uv run prek run check-json --all-files
      - name: 🚀 Check for merge conflicts
        run: uv run prek run check-merge-conflict --all-files
      - name: 🚀 Check for broken symlinks
        run: uv run prek run check-symlinks --all-files
      - name: 🚀 Check TOML files
        run: uv run prek run check-toml --all-files
      - name: 🚀 Check XML files
        run: uv run prek run check-xml --all-files
      - name: 🚀 Check YAML files
        run: uv run prek run check-yaml --all-files
      - name: 🚀 Detect Private Keys
        run: uv run prek run detect-private-key --all-files
      - name: 🚀 Check End of Files
        run: uv run prek run end-of-file-fixer --all-files
      - name: 🚀 Trim Trailing Whitespace
        run: uv run prek run trailing-whitespace --all-files

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v7.0.1
      - name: 🏗 Set up uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          enable-cache: true
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: 🐍 Install Python
        run: uv python install
      - name: 🏗 Install dependencies
        run: uv sync --locked
      - name: 🚀 Run yamllint
        run: uv run yamllint .
