---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
  workflow_call:

permissions:
  contents: read

jobs:
  pr_labels:
    name: Verify
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: 🏷 Verify PR has a valid label
        uses: klaasnicolaas/action-pr-labels@v3.1.1
        with:
          valid-labels: >-
            breaking-change, bugfix, documentation, enhancement,
            refactor, performance, new-feature, maintenance, ci, dependencies
