---
name: Typing

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.12"

jobs:
  ty:
    name: ty
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v7.0.1
      - name: 🏗 Set up uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          enable-cache: true
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: 🐍 Install Python
        run: uv python install
      - name: 🏗 Install dependencies
        run: uv sync --locked
      - name: 🚀 Run ty
        run: uv run ty check examples src tests
